---
kind: Service
apiVersion: v1
metadata:
  name: cyntest-service
spec:
  selector:
    app: cyntest
  ports:
  - port: 80
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyntest
spec:
  selector:
    matchLabels:
      app: cyntest
  replicas: 4
  template:
    metadata:
      labels:
        app: cyntest
    spec:
      containers:
      - name: cyntest
        image: bitcynth/cyntest:latest
        ports:
        - containerPort: 5000

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cyntest-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - cyntest.cynthia.re
    secretName: letsencrypt-prod
  rules:
  - host: cyntest.cynthia.re
    http:
      paths:
      - backend:
          serviceName: cyntest-service
          servicePort: 80